name: Release

on:
  release:
    types: [ published ]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      name: ${{ github.ref_name }}

  release:
    name: Release ${{ github.ref_name }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download ${{ github.ref_name }}.tar.gz artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ github.ref_name }}.tar.gz

    - name: Download ${{ github.ref_name }}.sha512sum artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ github.ref_name }}.sha512sum

    - name: Upload ${{ github.ref_name }}.{tar.gz,sha512sum} to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run:
        gh -R ${{ github.repositoryUrl }} release upload ${{ github.ref_name }} ${{ github.ref_name }}.{tar.gz,sha512sum}
